### ISSUE TITLE
RX 550 2GB Support ?

### ISSUE THREAD

**Issue by fatihdemirbal** [d0kur0/hackintosh-preset#1]
GPU Buyers Guide says " Catalina dont support RX550", your rx550 support natively?

**Comment by d0kur0** [comment]
Yes, everything worked for me right away, without any additional actions. whatevergreen.kext and lilu.kext did it all. 
(c) Google Translate

**Comment by fatihdemirbal** [comment]
thanks for your answer. which brand rx 550 are you using?

**Comment by d0kur0** [comment]
ASUS AMD Radeon RX 550 AREZ [AREZ-PH-RX550-2G].

**Comment by fatihdemirbal** [comment]
thanks.

**Comment by erickacevedor** [comment]
Was about to ask the same question as @fatihdemirbal since I read the same thing regarding the lack of compatibility of the RX 550 2GB card. But, I'll try and do the hackintosh!

**Comment by fatihdemirbal** [comment]
you can check, https://www.reddit.com/r/hackintosh/comments/fy0yks/msi_z270_7700k_gtx_1070_ti_disabled_sapphire/
