### ISSUE TITLE
Instructions for a newbie hackintosher?

### ISSUE THREAD

**Issue by erickacevedor** [d0kur0/hackintosh-preset#3]
Hey pal! Happy new year! Hope you spent the holiday with your loved ones!
On the other hand, I would like to know if you can help me installing MacOS on my AMD-based PC using your GPU model. I have a RX550 2GB too and I read  in some forums that this card is no longer supporter for hackintosh. 

I'm new on this type of AMD-based hackintosh and dont have many things clear, hope you can give me a hand, I could buy you a coffee if you like :)

**Comment by d0kur0** [comment]
Hi, I will make a reservation in advance that I use google translator. I will not tell you that I myself am experienced in this matter. I have been using this guide - https://dortania.github.io/OpenCore-Install-Guide I was able to figure it out, even with little knowledge of English. Problems along the way were usually solved using Google. You are not the first who writes to me that this video card is not supported, but it works for me, maybe you will not have any problems either. The guide that I threw off is part of the Dortania project, they have their own subreddit and discord channel, I think if you have problems, someone can help you.

**Comment by erickacevedor** [comment]
No problem buddy! Thanks anyway for your help pal!

**Comment by d0kur0** [comment]
@erickacevedor 
The main thing is not to give up) I managed to do it somewhere from the third time. I cannot help because the installation process is very different depending on the hardware. I might be able to help if our hardware matches.

But you have a trump card - knowledge of the English language.
